name: Windows

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile
      run: |
        echo "build start"
        dir
        cl.exe /Fe:sqinn.exe lib\*.c
        dir
        echo "executing test"
        .\sqinn2.exe -test
        md dist
        copy sqinn2.exe dist
        echo "build done"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-windows-amd64
        path: dist

